### ISSUE TITLE
./prof/bench crashes

### ISSUE THREAD

**Issue by sir-sigurd** [llllllllll/cnamedtuple#9]
```
╰─$ ./prof/bench
Running with: Python 3.6.2 (default, Jul 17 2017, 13:39:29) [GCC 6.4.0 20170704]

type creation from string with 1 field(s): namedtuple('NT', 'a')
  collections: Traceback (most recent call last):
  File "./prof/bench", line 152, in <module>
    main()
  File "./prof/bench", line 143, in main
    ratio.extend(run_test(v, args.n))
  File "./prof/bench", line 89, in run_test
    print(collections.format())
AttributeError: 'Benchmark' object has no attribute 'format'
```

**Comment by llllllllll** [comment]
What version of `perf` are you using? I have tested with 0.9.4.

**Comment by sir-sigurd** [comment]
I tried to run it with `perf==1.4` and `perf==1.3`.

**Comment by llllllllll** [comment]
The API may have changed since this was written, could you try with 0.9.4 and see if you still get an error?
